In [1]:
#Problem 1
import numpy as np
#1
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

Empty Array (2x2):
[[4.88859591e-310 0.00000000e+000]
 [6.81632885e+040 6.66051914e-310]]


In [2]:
#2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):")
print(ones_array)


All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#3
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nFilled Array (3x3 with 7):")
print(filled_array)


Filled Array (3x3 with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
#4
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)
print("\nZeros-like Array (same shape as existing array):")
print(zeros_like_array)


Zeros-like Array (same shape as existing array):
[[0 0]
 [0 0]]


In [5]:
#5
ones_like_array = np.ones_like(existing_array)
print("\nOnes-like Array (same shape as existing array):")
print(ones_like_array)


Ones-like Array (same shape as existing array):
[[1 1]
 [1 1]]


In [6]:
#6
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy Array from list:")
print(numpy_array)


Numpy Array from list:
[1 2 3 4]


In [27]:
#Problem_2
#1
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_to_49)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
#2
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3)


3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
#3
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)



3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#4
random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("\nRandom Array of size 30 and its mean:", mean_random_array)


Random Array of size 30 and its mean: 0.43179361918681985


In [31]:
#5
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array, Min value:", min_value, ", Max value:", max_value)


10x10 Random Array, Min value: 0.00473081032716649 , Max value: 0.993750751835817


In [32]:
#6
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced with 1:")
print(zero_array)


Zero Array with 5th element replaced with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
#7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)


Reversed Array:
[0 4 0 0 2 1]


In [25]:
#8
border_ones = np.ones((5, 5))
border_ones[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:")
print(border_ones)


2D Array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
#9
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)


8x8 Checkerboard Pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [8]:
#Problem 3

import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1
addition_result = x + y
print("Addition of x and y:")
print(addition_result)


Addition of x and y:
[[ 6  8]
 [10 13]]


In [10]:
#2
subtraction_result = x - y
print("\nSubtraction of x and y:")
print(subtraction_result)


Subtraction of x and y:
[[-4 -4]
 [-4 -3]]


In [12]:
#3
multiplication_result = x * 2
print("\nMultiplying x with 2:")
print(multiplication_result)


Multiplying x with 2:
[[ 2  4]
 [ 6 10]]


In [11]:
#4
square_result = np.square(x)
print("\nSquare of each element of x:")
print(square_result)


Square of each element of x:
[[ 1  4]
 [ 9 25]]


In [14]:
#5
dot_v_w = np.dot(v, w)
print("\nDot product of v and w:")
print(dot_v_w)

dot_x_v = np.dot(x, v)
print("\nDot product of x and v:")
print(dot_x_v)

dot_x_y = np.dot(x, y)
print("\nDot product of x and y:")
print(dot_x_y)



Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]


In [15]:
#6
concat_x_y = np.concatenate((x, y), axis=0)
print("\nConcatenating x and y along rows:")
print(concat_x_y)

concat_v_w = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\nConcatenating v and w along columns:")
print(concat_v_w)


Concatenating x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along columns:
[[ 9 11]
 [10 12]]


In [16]:
#7
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nConcatenating x and v:")
    print(concat_x_v)
except ValueError as e:
    print("\nError encountered while concatenating x and v:", e)


Error encountered while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [18]:
# Problem 4

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
#1
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I (Identity Matrix):")
print(identity_matrix)

A * A^(-1) = I (Identity Matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [20]:
#2
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =")
print(AB)
print("\nBA =")
print(BA)

if np.array_equal(AB, BA):
    print("\nAB = BA")
else:
    print("\nAB != BA")


AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

AB != BA


In [21]:
#3
AB_T = np.transpose(AB)  # Transpose of AB
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T
print("\n(AB)^T = B^T * A^T:")
print("Transpose of AB:")
print(AB_T)
print("\nB^T * A^T:")
print(B_T_A_T)


(AB)^T = B^T * A^T:
Transpose of AB:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]


In [22]:
#4
A_system = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_system = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A_system), B_system)
print("\nSolution using inverse method (X = A^(-1) * B):")
print(X)


Solution using inverse method (X = A^(-1) * B):
[ 2.  1. -2.]


In [23]:
#5
X_linalg = np.linalg.solve(A_system, B_system)
print("\nSolution using np.linalg.solve:")
print(X_linalg)


Solution using np.linalg.solve:
[ 2.  1. -2.]
